name: Sync Files to RepoB
on:
  push:
    paths:
      - '**.txt'  
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repoA
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Get changed txt files
        id: changed-files
        run: |
          git fetch origin ${{ github.event.before }}
          echo "files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- '*.txt' | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Clone and sync repoB
        if: steps.changed-files.outputs.files != ''
        run: |
          echo "Sincronizando arquivos: ${{ steps.changed-files.outputs.files }}"
          
          # Clone repoB
          git clone https://andremadu:${{ secrets.GH_TOKEN }}@github.com/andremadu/repoB.git
          
          # Copiar arquivos para repoB
          cd repoB
          for file in ${{ steps.changed-files.outputs.files }}; do
            mkdir -p "$(dirname "$file")"
            cp "../$file" "$file"
          done
          
          # Commit e push para repoB
          git config user.name "andremadu"
          git config user.email "andremm2412@gmail.com"
          git add .
          git diff --cached --quiet || git commit -m "Sync files from repoA" && git push origin main
