name: Sync Files to RepoB

on:
  push:
    paths:
      - '**.txt'  

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repoA
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Traz pelo menos dois commits para comparação

      - name: Clone repoB
        run: |
          git clone https://andremadu:${{ secrets.GH_TOKEN }}@github.com/andremadu/repoB.git
          cd repoB

          # Comparação com o commit anterior
          changed_files=$(git diff --name-only HEAD~1 HEAD -- '*.txt' || true)

          if [ -z "$changed_files" ]; then
            echo "Nenhum ficheiro .txt para sincronizar."
            exit 0
          fi

          echo "Ficheiros a copiar: $changed_files"

          # Copiar os ficheiros para repoB mantendo a estrutura
          for file in $changed_files; do
            mkdir -p "$(dirname "repoB/$file")"
            cp --parents "$file" repoB/
          done

          cd repoB
          git config user.name "andremadu"
          git config user.email "andremm2412@gmail.com"

          git add .
          if git diff --cached --quiet; then
            echo "Nenhuma alteração para sincronizar."
          else
            git commit -m "Sync files from repoA"
            git push origin main
          fi

