name: Sync Files to RepoB

on:
  push:
    paths:
      - '**.txt'  

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repoA
        uses: actions/checkout@v3

      - name: Clone repoB
        run: |
          git clone https://andremadu:${{ secrets.GH_TOKEN }}@github.com/andremadu/repoB.git
          cd repoB

          # Copia apenas os ficheiros adicionados/modificados no commit
          for file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- '*.txt'); do
            cp "../$file" .
          done

          git config user.name "andremadu"
          git config user.email "andremm2412@gmail.com"

          git add .
          if git diff --cached --quiet; then
            echo "Nenhuma alteração para sincronizar."
          else
            git commit -m "Sync files from repoA"
            git push origin main
          fi
